### ISSUE TITLE
Combine multiple bitmap into a single png

### ISSUE THREAD

**Issue by S1M0N38** [Fred31-pavel-sokov/SupercellSWF#1]
Hi,
this is not an issue but an "How to" question (I wrote here because I cannot find your discord nor other way to contact you directly).

```python
from sc import SupercellSWF

swf = SupercellSWF()
swf.load("chr_knight.sc")
swf.textures[0].image.save("chr_knight.png")
```
successfully load the Clash Royale knight and produce the following sprite sheet in png format.

![chr_knight](https://user-images.githubusercontent.com/22257750/142288569-e8dfc5bd-7f81-4283-958d-8ee6f2786a18.png)

In this `swf` object there are 486 shapes:
- 243 contains one bitmap (only blue knight)
- 243 contains two bitmaps (blue knight and the red thing)

I am interested in obtain individual image of the knight (blue and red) from any point of view so I iterate over shapes.

```python
for i, shape in enumerate(swf.shapes):
    if len(shape.bitmaps) == 2:
        shape.bitmaps[0].to_image(f"shape{i}_knight_.png")
        shape.bitmaps[1].to_image(f"shape{i}_red_stuff.png")
``` 

This will produce two png for every shape: one for the blue knight and one for the correspondent red thing. In order to produce the red knight (I think) I have to put the red stuff over the blue knight; the problem is that the red stuff must be rotated by **some amount** (and maybe sometimes flip, not sure).

My problem is that I cannot found the **amount** of rotation required to produce the "every angle" image also for the red knight. Is there a way to obtain this angle or produce directly the red knight combining different bitmaps inside SupercellSWF?

**Comment by Fred31-pavel-sokov** [comment]
Soon I will add the correct saving of bitmaps and shapes (with rotation, etc.). I hope I can do it as soon as possible for you.

**Comment by Fred31-pavel-sokov** [comment]
Done.
